#!/bin/bash
# Grafana Cloud Credentials Setup Guide
# ==========================================

echo "🔐 GRAFANA CLOUD CREDENTIALS SETUP"
echo "=================================="
echo ""
echo "Follow these steps to get your credentials:"
echo ""
echo "1. PROMETHEUS CREDENTIALS:"
echo "   - Go to: https://ayazzssaifi.grafana.net/connections/datasources"
echo "   - Click on 'grafanacloud-ayazzssaifi-prom' (your default Prometheus)"
echo "   - Scroll down to 'Auth' section"
echo "   - Username: Copy the 'User' field"
echo "   - Password: You need to create an Access Policy Token"
echo ""
echo "2. CREATE ACCESS POLICY TOKEN:"
echo "   - Go to: https://ayazzssaifi.grafana.net/a/grafana-auth-app/service-accounts"
echo "   - Click 'Add service account token' or 'Create token'"
echo "   - Name it: 'microservices-demo-monitoring'"
echo "   - Set scopes: metrics:write, logs:write"
echo "   - Copy the generated token (you won't see it again!)"
echo ""
echo "3. LOKI CREDENTIALS:"
echo "   - Go to: https://ayazzssaifi.grafana.net/connections/datasources"
echo "   - Find 'grafanacloud-ayazzssaifi-logs' (your Loki instance)"
echo "   - Same username as Prometheus"
echo "   - Same token as above"
echo ""
echo "4. UPDATE THE SECRET FILE:"
echo "   - Edit: monitoring/grafana-credentials-secret.yaml"
echo "   - Replace YOUR_PROMETHEUS_USERNAME with the user number"
echo "   - Replace YOUR_GRAFANA_CLOUD_ACCESS_POLICY_TOKEN with token"
echo ""
echo "Example values from your dashboard URL:"
echo "  Prometheus URL: https://prometheus-prod-43-prod-ap-south-1.grafana.net"
echo "  Loki URL: https://logs-prod-006.grafana.net (or similar)"
echo ""
echo "After updating, run:"
echo "  kubectl apply -f monitoring/grafana-credentials-secret.yaml"
echo ""
